pipeline {
    agent any

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'prod'], description: 'Select target environment (dev or prod)')
        choice(name: 'ACTION', choices: ['deploy', 'stop', 'remove'], description: 'Choose action to perform')
    }

    environment {
        DB_CONTAINER_NAME = "sak-mysql-dev"
        SPRING_CONTAINER_NAME = "sak-spring-dev"
        SPRING_IMAGE_NAME = "sak-spring-dev"
        DB_ROOT_PASSWORD = "1234"
        DB_NAME = "mydb"
        DB_PORT = "3306"
        APP_PORT = "8088"
        SPRING_PROFILE = "dev"
    }


    stages {
        stage('Deploy Application Dev Environment') {
            when {
                allOf {
                    expression { params.ENVIRONMENT == 'dev' }
                    expression { params.ACTION == 'deploy' }
                }
            }
            steps {
                echo "🚀 Deploying Spring + MySQL Dev Environment..."
                sh """
                cd ${WORKSPACE}/app_server
                export DB_CONTAINER_NAME=$DB_CONTAINER_NAME
                export SPRING_CONTAINER_NAME=$SPRING_CONTAINER_NAME
                export SPRING_IMAGE_NAME=$SPRING_IMAGE_NAME
                export DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
                export DB_NAME=$DB_NAME
                export DB_PORT=$DB_PORT
                export APP_PORT=$APP_PORT
                export SPRING_PROFILE=$SPRING_PROFILE
                sudo docker-compose up -d --build
                """
            }
        }
        stage('Stop Dev Environment') {
            when {
                allOf {
                    expression { params.ENVIRONMENT == 'dev' }
                    expression { params.ACTION == 'stop' }
                }
            }
            steps {
                echo "🛑 Stopping Dev Containers..."
                sh """
                cd ${WORKSPACE}/app_server
                export DB_CONTAINER_NAME=$DB_CONTAINER_NAME
                export SPRING_CONTAINER_NAME=$SPRING_CONTAINER_NAME
                sudo docker-compose stop
                """
            }
        }
        stage('Remove Dev Environment') {
            when {
                allOf {
                    expression { params.ENVIRONMENT == 'dev' }
                    expression { params.ACTION == 'remove' }
                }
            }
            steps {
                echo "❌ Removing Dev Containers & Volume..."
                sh """
                cd ${WORKSPACE}/app_server
                export DB_CONTAINER_NAME=$DB_CONTAINER_NAME
                export SPRING_CONTAINER_NAME=$SPRING_CONTAINER_NAME

                sudo docker-compose down -v
                """
            }
        }
    }

    post {
        success {
            echo "✅ Spring Boot container is handled successfully."
        }
        failure {
            echo "❌ Something went wrong with the deployment."
        }
        always {
            echo "ℹ️ Pipeline finished. Check logs above for final status."
        }
    }
}
