pipeline {
    agent any

    parameters {
        choice(name: 'ACTION', choices: ['DEPLOY', 'REMOVE'], description: 'Choose action to perform')
    }

    environment {
        PROJECT_NAME = 'SakApp'
        DOCKER_COMPOSE_DIR = "dev_env"
    }

    stages {
        stage('Deploy Application in DEV Environment') {
            when {
                expression { return params.ACTION == 'DEPLOY' }
            }
            steps {
                echo "Deploying DEV environment..."

                dir("${DOCKER_COMPOSE_DIR}") {
                    sh "docker compose build"
                    sh "docker compose up -d"
                }
            }
        }
        stage('Remove Application in DEV Environment') {
            when {
                expression { return params.ACTION == 'REMOVE' }
            }
            steps {
                echo "Removing DEV environment..."

                dir("${DOCKER_COMPOSE_DIR}") {
                    sh "docker compose down --remove-orphans"
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline finished.'
        }
        success {
            echo 'Pipeline succeeded.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}